# Generated by Django 5.2.2 on 2025-06-30 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategori Adı')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Mekan Adı')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adres')),
                ('city', models.CharField(max_length=100, verbose_name='Şehir')),
                ('main_photo', models.ImageField(blank=True, null=True, upload_to='location_photos/', verbose_name='Ana Fotoğraf')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('location_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='travelog.category', verbose_name='Mekan Türü')),
            ],
            options={
                'verbose_name': 'Mekan',
                'verbose_name_plural': 'Mekanlar',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Rota Adı')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL Dostu İsim')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='route_images/', verbose_name='Ana Rota Görseli')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan Rota (Slider İçin)')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('locations', models.ManyToManyField(blank=True, related_name='routes', to='travelog.location', verbose_name='Bu Rota İçindeki Mekanlar')),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotalar',
                'ordering': ['-date_created'],
            },
        ),
    ]
