# Generated by Django 5.2.2 on 2025-06-30 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelog', '0003_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='travelog.category', verbose_name='Mekan Türü'),
        ),
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL Dostu İsim'),
        ),
        migrations.CreateModel(
            name='LocationMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='location_extra_media/', verbose_name='Medya Dosyası')),
                ('media_type', models.CharField(choices=[('image', 'Resim'), ('video', 'Video')], default='image', max_length=10, verbose_name='Medya Türü')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Açıklama')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='travelog.location', verbose_name='Mekan')),
            ],
            options={
                'verbose_name': 'Mekan Medyası',
                'verbose_name_plural': 'Mekan Medyaları',
                'ordering': ['order', 'id'],
            },
        ),
    ]
